[package]
name = "xbingo"
version = "0.0.1"
authors = [ "DrDelphi",]
edition = "2018"
publish = false

[lib]
path = "src/xbingo.rs"

[dependencies.elrond-wasm]
version = "0.32.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.32.0"
